name: Deploy PRD

on:
  release:
    types: [created]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
          echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        id: systemDate
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            cd /opt/reactjs/meeteam-portal-front
            mv /opt/reactjs/meeteam-portal-front/build/ /opt/releases/meeteam-portal/frontend/meeteam-portal_${{ steps.systemDate.outputs.date }}
            git reset --hard HEAD
            git pull --force
            cp /opt/applicationconfig/meeteam-portal-front-config.env /opt/reactjs/meeteam-portal-front/.env
            npm install
            npm run build
            rm -r /var/www/mbc/reactjs/meeteam-portal
            cp -r /opt/reactjs/meeteam-portal-front/build/ /var/www/mbc/reactjs/meeteam-portal
